# Generated by Django 4.2.6 on 2023-12-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_comments_postcomment'),
        ('comments', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
