# Generated by Django 4.2.6 on 2023-12-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
