# Generated by Django 4.2.6 on 2023-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default.png', upload_to='users/avatars'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_engines',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.engine'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='links',
            field=models.ManyToManyField(blank=True, to='users.link'),
        ),
    ]
