# Generated by Django 4.2.6 on 2023-11-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_links_remove_engine_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='image',
            field=models.ImageField(default='engines/default.png', upload_to='engines'),
        ),
    ]
