# Generated by Django 4.2.6 on 2023-11-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0004_engine_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_engines',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.engine'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.status', to_field='name'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
