# Generated by Django 4.2.6 on 2023-12-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_subscribes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscribes',
            new_name='subscriptions',
        ),
    ]
