# Generated by Django 4.2.6 on 2024-01-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_banned',
        ),
    ]
